name = "xolar-live-tailwind-astro"
pages_build_output_dir = "dist"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "xolar-db"
database_id = "your-database-id"  # Replace with actual D1 database ID after creation

[env.production]
# Production environment settings
routes = [
  { pattern = "xolar.ca", zone_name = "xolar.ca" },
  { pattern = "www.xolar.ca", zone_name = "xolar.ca" }
]

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id"

# Production D1 Database
[[env.production.d1_databases]]
binding = "DB"
database_name = "xolar-db-production"
database_id = "your-production-database-id"  # Replace with production D1 database ID

[build]
command = "npm run build"
cwd = "./"

[build.environment_variables]
NODE_VERSION = "18"

# Cache settings for static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/sitemap*.xml"
[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/robots.txt"
[headers.values]
Cache-Control = "public, max-age=3600"